.ifndef __COP_INC__
__COP_INC__:


DPCOP_Y			:=	1 	; offset of Y in COP entry/exit frame
DPCOP_X			:=  3	; offset of X in COP entry/exit frame
DPCOP_AH		:=  5	; offset of AH in COP entry/exit frame
DPCOP_B			:=	7	; offset of B(ank) in COP entry/exit frame
DPCOP_DP		:=	8	; offset of DP in COP entry/exit frame
DPCOP_P			:= 10	; offset of P in COP entry/exit frame
DPCOP_PC		:= 11	; offset of PC in COP entry/exit frame
DPCOP_K			:= 13	; offset of K (program bank) in COP entry/exit frame

.endif